### ISSUE TITLE
Module pandas is not mentioned in requirements.txt

### ISSUE THREAD

**Issue by angkasawan2007** [jclark1913/osint-google-analytics#8]
Not a big issue just slight inconvenience 
`Traceback (most recent call last):
 File "/home/langley/SOFT/osint-google-analytics/main.py", line 14, in <module>
    from osint_ga.output import (
  File "/home/langley/SOFT/osint-google-analytics/osint_ga/output.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'`

**Comment by jclark1913** [comment]
Cheers Daniel, great catch! Pandas and XlsxWriter have been added to requirements, so this issue is now resolved on main.
